name: Build and publish documentation

on:
  push:
    branches: [master]
    tags:
      - '*'
  
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
# concurrency:
#  group: "pages"
#  cancel-in-progress: false

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.

      - name: prepare dependences
        run: |
          pip install -r docs/requirements.txt

      - name: build docs
        run: |
          sphinx-multiversion docs docs/_build/versioned

      - name: commit documentation changes
        run: |
          git checkout gh-pages
          for dirname in docs/_build/versioned/*; do mv "$dirname" "$(basename $dirname)" && git add "$(basename $dirname)"; done
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # that.

      - name: Push changes
        if: github.ref == 'refs/heads/master'
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
